name: Build project

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]
    
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.0.app && /usr/bin/xcodebuild -version
    - name: Build
      run: xcodebuild build-for-testing -scheme TestLocalisationProject build -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 11 Pro'
