name: Check localisation strings by UnitTests

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        testPlan: [English, Ukrainian]
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.0.app && /usr/bin/xcodebuild -version
    - name: Run ${{ matrix.testPlan }} Test Plan
      run: xcodebuild test-without-building -scheme TestLocalisationProject -project TestLocalisationProject.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=15.0' -testPlan ${{ matrix.testPlan }}

