name: Swift

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.0.app && /usr/bin/xcodebuild -version
    - name: Build
      run: xcodebuild -scheme TestLocalisationProject build -destination 'platform=iOS Simulator,OS=14.4,name=iPhone 11 Pro' | xcpretty && exit ${PIPESTATUS[0]}
    - name: Run English Test Plan
      run: xcodebuild test -scheme TestLocalisationProject -project TestLocalisationProject.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=14.4' -testPlan English | xcpretty && exit ${PIPESTATUS[0]}
    - name: Run Ukrainian Test Plan
      run: xcodebuild test -scheme TestLocalisationProject -project TestLocalisationProject.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=14.4' -testPlan Ukrainian | xcpretty && exit ${PIPESTATUS[0]}
