name: Swift

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - name: Select Xcode version
        - uses: maxim-lobanov/setup-xcode@v1
        with:
            xcode-version: latest-stable
    - name: Checkout
        uses: actions/checkout@v3
    - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
    - name: Build
        env:
            scheme: ${{ 'default' }}
            platform: ${{ 'iOS Simulator' }}
        run: xcodebuild -scheme TestLocalisationProject build -destination 'platform=$platform,name=$device'
    - name: Run English Test Plan
        env:
            scheme: ${{ 'default' }}
            platform: ${{ 'iOS Simulator' }}
        run: xcodebuild test -scheme TestLocalisationProject -project TestLocalisationProject.xcodeproj -destination 'platform=$platform,name=$device' -testPlan English
    - name: Run Ukrainian Test Plan
        env:
            scheme: ${{ 'default' }}
            platform: ${{ 'iOS Simulator' }}
        run: xcodebuild build-for-testing -scheme TestLocalisationProject -project TestLocalisationProject.xcodeproj -destination 'platform=$platform,name=$device' -testPlan Ukrainian
